version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: caixadb
      POSTGRES_USER: caixauser
      POSTGRES_PASSWORD: caixapassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
#TODO: DESCOMENTAR
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: caixamanager-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/caixadb
#      SPRING_DATASOURCE_USERNAME: caixauser
#      SPRING_DATASOURCE_PASSWORD: caixapassword
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
  postgres_data:
    driver: local

